### ISSUE TITLE
TCK tests pass individually but fail when run as a suite

### ISSUE THREAD

**Issue by VaughnVernon** [reactive-streams/reactive-streams-jvm#474]
I am sure I must have a problem in my `pom.xml` or similar. If I override any number of tests and run them individually, every test works. When I run them as a suite I get 21 or so failures.

See the overrides (commented out) here:

https://github.com/vlingo/vlingo-streams/blob/a51e7a107e9218077c74203e7377351557f0a74f/vlingo-streams-tck/src/test/java/io/vlingo/reactivestreams/StreamPublisherCompatibilityTest.java#L167

If I test as follows it passes:

```
mvn -Dtest=StreamPublisherCompatibilityTest#required_spec317_mustSupportACumulativePendingElementCountUpToLongMaxValue clean test
````

If I test as follows it fails several tests:

```
mvn -Dtest=StreamPublisherCompatibilityTest clean test
````

I have attempted to adjust the timeouts to allow potentially slow tests, but it makes no difference.

https://github.com/vlingo/vlingo-streams/blob/a51e7a107e9218077c74203e7377351557f0a74f/vlingo-streams-tck/src/test/java/io/vlingo/reactivestreams/StreamPublisherCompatibilityTest.java#L25

Any pointers in running TestNG or whatever is much appreciated.

**Comment by akarnokd** [comment]
What are the failures? Timeouts for elements? Does your publisher work outside the TCK? Are you using Java's ForkJoinPool somewhere?

**Comment by VaughnVernon** [comment]
> What are the failures? 

Errors below at bottom.

> Timeouts for elements? 

Apparently there are timeouts, which are after 2 seconds each. That's nonsense. All of our own tests pass in a few milliseconds, and running the TCK tests independently complete in a few milliseconds.

```
Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@166fa74d to Publisher org.reactivestreams.Publisher__Proxy@40f08448 within 2000 ms
```

> Does your publisher work outside the TCK? 

Yes, all of our own tests pass.

> Are you using Java's ForkJoinPool somewhere?

No, we use `ThreadPoolExecutor`.

**Errors:**

```
[ERROR] Failures: 
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.optional_spec105_emptyStreamMustTerminateBySignallingOnComplete:412->PublisherVerification.optionalActivePublisherTest:1163->createPublisher:31
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_createPublisher1MustProduceAStreamOfExactly1Element:162->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@166fa74d to Publisher org.reactivestreams.Publisher__Proxy@40f08448 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_createPublisher3MustProduceAStreamOfExactly3Elements:179->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@7181ae3f to Publisher org.reactivestreams.Publisher__Proxy@46238e3f within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec101_subscriptionRequestMustResultInTheCorrectNumberOfProducedElements:211->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@1efee8e7 to Publisher org.reactivestreams.Publisher__Proxy@1ee807c6 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec102_maySignalLessThanRequestedAndTerminateSubscription:239->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@679b62af to Publisher org.reactivestreams.Publisher__Proxy@5cdd8682 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec105_mustSignalOnCompleteWhenFiniteStreamTerminates:397->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@290dbf45 to Publisher org.reactivestreams.Publisher__Proxy@12028586 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec107_mustNotEmitFurtherSignalsOnceOnCompleteHasBeenSignalled:430->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@11c20519 to Publisher org.reactivestreams.Publisher__Proxy@70beb599 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec109_mustIssueOnSubscribeForNonNullSubscriber:477->PublisherVerification.activePublisherTest:1141->createPublisher:31
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec109_subscribeThrowNPEOnNullSubscriber:461->PublisherVerification.activePublisherTest:1141->createPublisher:31
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec302_mustAllowSynchronousRequestCallsFromOnNextAndOnSubscribe:721->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.PublisherVerification$18$1@3444d69d to Publisher org.reactivestreams.Publisher__Proxy@1372ed45 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec303_mustNotAllowUnboundedRecursion:752->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.PublisherVerification$19$2@6c3f5566 to Publisher org.reactivestreams.Publisher__Proxy@12405818 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec306_afterSubscriptionIsCancelledRequestMustBeNops:844->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.PublisherVerification$20$1@442675e1 to Publisher org.reactivestreams.Publisher__Proxy@6166e06f within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec307_afterSubscriptionIsCancelledAdditionalCancelationsMustBeNops:877->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@49070868 to Publisher org.reactivestreams.Publisher__Proxy@6385cb26 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec309_requestNegativeNumberMustSignalIllegalArgumentException:908->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@1e9e725a to Publisher org.reactivestreams.Publisher__Proxy@15d9bc04 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec309_requestZeroMustSignalIllegalArgumentException:897->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@797badd3 to Publisher org.reactivestreams.Publisher__Proxy@77be656f within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec312_cancelMustMakeThePublisherToEventuallyStopSignaling:943->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@78a2da20 to Publisher org.reactivestreams.Publisher__Proxy@dd3b207 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec313_cancelMustMakeThePublisherEventuallyDropAllReferencesToTheSubscriber:1014->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@7364985f to Publisher org.reactivestreams.Publisher__Proxy@5d20e46 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec317_mustNotSignalOnErrorWhenPendingAboveLongMaxValue:1078->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.PublisherVerification$30$1@b7f23d9 to Publisher org.reactivestreams.Publisher__Proxy@61d47554 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec317_mustSupportACumulativePendingElementCountUpToLongMaxValue:1055->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@5a4aa2f2 to Publisher org.reactivestreams.Publisher__Proxy@6591f517 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.required_spec317_mustSupportAPendingElementCountUpToLongMaxValue:1037->PublisherVerification.activePublisherTest:1142 Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@58134517 to Publisher org.reactivestreams.Publisher__Proxy@4450d156 within 2000 ms
[ERROR]   StreamPublisherCompatibilityTest>PublisherVerification.stochastic_spec103_mustSignalOnMethodsSequentially:255->PublisherVerification.stochasticTest:1211->PublisherVerification.activePublisherTest:1142 Failed in iteration 0 of 100. Expected completion signal after signalling 10 elements (signalled 0), yet did not receive it within 20000 ms
[INFO] 
[ERROR] Tests run: 38, Failures: 21, Errors: 0, Skipped: 12
```

**Comment by akarnokd** [comment]
I'm having trouble building your project: 
- Cannot resolve io.vlingo:vlingo-actors:0.9.3-RC4
- Cannot resolve io.vlingo:vlingo-http:0.9.3-RC4

**Comment by VaughnVernon** [comment]
Sorry. I have updated the pom.xml to use Maven Central and version 1.0.0 artifacts.

`<url>https://repo.maven.apache.org/maven2</url>`

Please pull from the root and clean install.

**Comment by akarnokd** [comment]
Here are the failures I get:
#### optional_spec105_emptyStreamMustTerminateBySignallingOnComplete
```
java.lang.AssertionError
	at io.vlingo.reactivestreams.source.LongRangeSource.<init>(LongRangeSource.java:20)
```
Because `elements == 0` and your range doesn't like that.

#### required_createPublisher1MustProduceAStreamOfExactly1Element and the rest

I debugged into this and found that `ExecutorDispatcher.execute` doesn't run because `this.closed` is true and skips the subscribe message. One of the earlier tests (possibly `optional_spec111_multicast_mustProduceTheSameElementsInTheSameSequenceToAllOfItsSubscribersWhenRequestingManyUpfrontAndCompleteAsExpected`) triggers this close:
StreamPublisherDelegate.processNext Line 115: `stoppable.stop()` when `maybeElements.terminated` is true.

**Comment by akarnokd** [comment]
> Please pull from the root and clean install.

Doesn't work. You have a bunch of     

```xml
<properties>
        <vlingo.version>0.9.3-RC4</vlingo.version>
</properties>
```
That prevents pulling in 1.0.0:

https://github.com/vlingo/vlingo-streams/blob/master/vlingo-streams-core/pom.xml#L36 -> https://github.com/vlingo/vlingo-streams/blob/master/vlingo-streams-core/pom.xml#L54

https://github.com/vlingo/vlingo-streams/blob/master/vlingo-streams-pipes/pom.xml#L14 -> https://github.com/vlingo/vlingo-streams/blob/master/vlingo-streams-pipes/pom.xml#L27 & https://github.com/vlingo/vlingo-streams/blob/master/vlingo-streams-pipes/pom.xml#L32

https://github.com/vlingo/vlingo-streams/blob/master/vlingo-streams-tck/pom.xml#L36 ->

**Comment by VaughnVernon** [comment]
Oops! I missed a few lines. It is now fixed.

I need to fix `LongRangeSource` as you indicate. Almost there.

**Comment by VaughnVernon** [comment]
@akarnokd The `LongRangeSource` is fixed (commit pushed). It appears that the entire suite now passes. Please confirm on your side.

**Comment by akarnokd** [comment]
`optional_spec105_emptyStreamMustTerminateBySignallingOnComplete` passes but 19 other still don't, same subscribe timeout.

![image](https://user-images.githubusercontent.com/1269832/72598365-f8390300-390f-11ea-8e71-b63182d591f2.png)

**Comment by VaughnVernon** [comment]
@akarnokd Thanks much for your help! I have to catch a flight in a few hours but will try to dig in. I've been trying to figure out how to debug. Maybe now I can do so. In case you have more time I will sure accept more hints. :+1:

**Comment by akarnokd** [comment]
Your actor library seems to share one underlying `ExecutorDispatcher` (`ConcurrentQueueMailboxPlugin.executorDispatcher`) and even though you create distinct mailboxes, closing a mailbox closes the dispatcher (`ConcurrentQueueMailbox.close`). `StreamPublisher`, when created, asks for a `Stoppable` protocol on self (`selfAs(Stoppable.class)`) which gets a proxy to a `ConcurrentMailBox` referencing that shared `ExecutorDispatcher`. When your stream ends, the whole setup gets closed and your publishers can no longer deliver any signals.

Here is an example TestNG test that fails because of this:

```java

  @Test
  public void moreActors()  throws Throwable {
    World world = World.startWithDefaults("streams");
    try {
      final Source<Long> source = Source.rangeOf(0, 10);

      final PublisherConfiguration configuration =
              PublisherConfiguration.with(
                      PublisherConfiguration.FastestProbeInterval,
                      Streams.DefaultMaxThrottle,
                      Streams.DefaultBufferSize,
                      OverflowPolicy.DropHead);

      final Definition definition = Definition.has(StreamPublisher.class, Definition.parameters(source, configuration));

      runAwait(world.actorFor(Publisher.class, definition));
      Thread.sleep(1000);
      runAwait(world.actorFor(Publisher.class, definition));
    } finally {
      world.terminate();
    }
  }

  void runAwait(Publisher<Long> p) throws Throwable {
    CountDownLatch cdl = new CountDownLatch(1);
    p.subscribe(new Subscriber<Long>() {

      @Override
      public void onSubscribe(Subscription subscription) {
        subscription.request(Long.MAX_VALUE);
      }

      @Override
      public void onNext(Long aLong) {
        System.out.println(aLong);
      }

      @Override
      public void onError(Throwable throwable) {
        throwable.printStackTrace();
        cdl.countDown();
      }

      @Override
      public void onComplete() {
        System.out.println("Done");
        cdl.countDown();
      }
    });
    Assert.assertTrue(cdl.await(5, TimeUnit.SECONDS));
  }
```

> I am not sure if I am running on JUnit or TestNG

It appears you might have been tricked by JUnit which, as far as I know, instantiates the whole test class over and over for each individual test, thus you have been getting fresh `World` objects and distinct `ExecutorDispatcher`s every time (not to mention, probably a lot of dangling worker threads).

TestNG instantiates the test class once so all TCK test run in the same world. If I change the TCK test like this:

```java
public class StreamPublisherCompatibilityTest extends PublisherVerification<Long> {

  World world;

  @BeforeMethod
  public void before() {
    world = World.startWithDefaults("streams");
  }

  @AfterMethod
  public void after() {
    world.terminate();
  }
```

All but one methods pass now.

#### required_spec101_subscriptionRequestMustResultInTheCorrectNumberOfProducedElements

```
[TCK-DEBUG] org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@157632c9::onSubscribe(SubscriptionController [id=19 count=0 maximum=0 remaining=0 unbounded=false])
[TCK-DEBUG] org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@157632c9::onNext(1)
[TCK-DEBUG] org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@157632c9::onNext(2)
[TCK-DEBUG] org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@157632c9::onNext(3)
[TCK-DEBUG] org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@157632c9::onNext(4)
[TCK-DEBUG] org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@157632c9::onNext(5)
[TCK-DEBUG] org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@157632c9::onComplete()



java.lang.AssertionError: Publisher org.reactivestreams.Publisher__Proxy@6ee12bacproduced unrequested  [5]
at org.reactivestreams.tck.PublisherVerification.required_spec101_subscriptionRequestMustResultInTheCorrectNumberOfProducedElements(PublisherVerification.java:226)
```

The internal implementation of your library is convoluted. It keeps looping the LongRangeSource::next if there is backpressure even though it already generated all items upfront. 

When the test issues the second `request(1)`, the `SubscriptionController` is at (count = 0, maximum = 2) and its `sendNext` will signal 2 items instead of just one, emitting 3 items total instead of just two.

When the test issues `request(2)` after that, the `SubscriptionController` is at (count = 0, maximum = 4) and `sendNext` will signal the remaining two items (but would signal 4 if the sequence was longer) and we are at 5 items emitted. 

So in total, 4 items requested by the test but 5 items emitted by the `SubscriptionController`.

**Comment by VaughnVernon** [comment]
@akarnokd Thanks for your excellent feedback!

> The internal implementation of your library is convoluted. It keeps looping the LongRangeSource::next if there is backpressure even though it already generated all items upfront.

1. I have probably misinterpreted the publisher rules here. This is my thinking:

- If the `Publisher` has reached the last of the publishable elements for a given `Subscriber` (request limit reached) I am buffering the elements up to the publisher's given maximum buffer size.
- If the publisher's given maximum buffer size is reached, I have a policy for dropping buffered elements: `DropHead`, `DropTail`, `DropCurrent`.
- If the `Source` indicates that there are no more elements, the `Publisher` will continue to periodically push any buffered elements until (1) all subscribers have no more buffered elements, (2) all subscribers have cancelled their subscription.
- The above favors all subscribers receiving all elements, but not always possible due to buffer size limits.

2. Regarding your final two observations:

> When the test issues the second request(1), the SubscriptionController is at (count = 0, maximum = 2) and its sendNext will signal 2 items instead of just one, emitting 3 items total instead of just two.

> When the test issues request(2) after that, the SubscriptionController is at (count = 0, maximum = 4) and sendNext will signal the remaining two items (but would signal 4 if the sequence was longer) and we are at 5 items emitted.

- I think that the above two observations are due to the way I have interpreted:

`required_spec317_mustSupportACumulativePendingElementCountUpToLongMaxValue()` 

- If the subscription still has `N` elements remaining and a `request(M)` is received, the resulting number of remain elements will be `N + M`. If I do not support this then the aforementioned 317 fails.

Please advise on the above replies 1 and 2.

**Comment by akarnokd** [comment]
Most likely the problem is you reset [count](https://github.com/vlingo/vlingo-streams/blob/master/vlingo-streams-core/src/main/java/io/vlingo/reactivestreams/SubscriptionController.java#L220) while accumulating the total requests, thus sendNext will emit more and more.

**Comment by VaughnVernon** [comment]
@akarnokd All required and optional tests are now passing. There is one stochastic test failing but we won't pursue a fix unless it becomes a user issue. Thanks again for getting me over the hump on TestNG mysteries.
